### ISSUE TITLE
Make some documentation

### ISSUE THREAD

**Issue by gianmarcomennecozzi** [aau-network-security/haaukins-store#1]
Make some documentation in order to describe what this haaukins components does.

**Comment by mrturkmen06** [comment]
Some information regarding to setting up dev environment added to [readme.md](https://github.com/aau-network-security/haaukins-store/blob/master/README.md) file and it is also available in github pages over [here](https://aau-network-security.github.io/haaukins-store/).

**Comment by gianmarcomennecozzi** [comment]
I think we can close this issue then :D
